CREATE TABLE IF NOT EXISTS auth (
    id BIGSERIAL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS matches (
    id BIGSERIAL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS store (
    id BIGSERIAL PRIMARY KEY
);
